"""add project_timelines and export_tasks tables

Revision ID: 680ffb3d0404
Revises: 33407b3f34bf
Create Date: 2026-03-23 10:07:37.247055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '680ffb3d0404'
down_revision = '33407b3f34bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###