"""add project model and foreign key constraints

Revision ID: a93089a31b33
Revises: 0d39df645aee
Create Date: 2026-03-23 16:32:29.914722

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a93089a31b33'
down_revision = '0d39df645aee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_tasks_project_id'), table_name='export_tasks')
    op.drop_index(op.f('ix_export_tasks_user_id'), table_name='export_tasks')
    op.drop_index(op.f('ix_export_tasks_user_status'), table_name='export_tasks')
    op.drop_table('export_tasks')
    op.drop_constraint(op.f('assets_project_id_fkey'), 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('user_id', sa.UUID(), nullable=False))
    op.add_column('projects', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('cover_image_url', sa.Text(), nullable=True))
    op.add_column('projects', sa.Column('duration_ms', sa.Integer(), server_default='0', nullable=False))
    op.add_column('projects', sa.Column('resolution_width', sa.Integer(), server_default='1920', nullable=False))
    op.add_column('projects', sa.Column('resolution_height', sa.Integer(), server_default='1080', nullable=False))
    op.add_column('projects', sa.Column('fps', sa.Float(), server_default='30.0', nullable=False))
    op.add_column('projects', sa.Column('status', sa.String(length=50), server_default='draft', nullable=False))
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.create_index(op.f('ix_projects_user_id'), 'projects', ['user_id'], unique=False)
    op.create_index('ix_projects_user_updated', 'projects', ['user_id', 'updated_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_projects_user_updated', table_name='projects')
    op.drop_index(op.f('ix_projects_user_id'), table_name='projects')
    op.alter_column('projects', 'name',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)
    op.drop_column('projects', 'status')
    op.drop_column('projects', 'fps')
    op.drop_column('projects', 'resolution_height')
    op.drop_column('projects', 'resolution_width')
    op.drop_column('projects', 'duration_ms')
    op.drop_column('projects', 'cover_image_url')
    op.drop_column('projects', 'description')
    op.drop_column('projects', 'user_id')
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(op.f('assets_project_id_fkey'), 'assets', 'projects', ['project_id'], ['id'], ondelete='SET NULL')
    op.create_table('export_tasks',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'queued'::character varying"), autoincrement=False, nullable=False),
    sa.Column('progress', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('format', sa.VARCHAR(length=50), server_default=sa.text("'mp4'::character varying"), autoincrement=False, nullable=False),
    sa.Column('resolution_width', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('resolution_height', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fps', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('video_bitrate_kbps', sa.INTEGER(), server_default=sa.text('4000'), autoincrement=False, nullable=False),
    sa.Column('output_key', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('download_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('export_tasks_pkey'))
    )
    op.create_index(op.f('ix_export_tasks_user_status'), 'export_tasks', ['user_id', 'status'], unique=False)
    op.create_index(op.f('ix_export_tasks_user_id'), 'export_tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_export_tasks_project_id'), 'export_tasks', ['project_id'], unique=False)
    # ### end Alembic commands ###